version: "3.2"
services:
#  app:
#    env_file:
#      - .env
#    container_name: nest.app
#    restart: always
#    build: .
#    ports:
#      - '${PORT}:${PORT}'
#    depends_on:
#      - mysql
#      - redis
#    environment:
#      DB_HOST: nest.mysql
#    networks:
#      - default

  mysql:
    image: mysql
    container_name: nest.mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DB_USERNAME}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'R00tP@ssW0rd'

    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - nest.mysql.data:/data/mysql
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: nest.redis
    ports:
      - '${REDIS_PORT}/tcp'
    volumes:
      - nest.redis.data:/data:rw
    networks:
      - default
    env_file:
      - .env


volumes:
  nest.mysql.data: {}
  nest.redis.data: {}

networks:
  default:
    driver: bridge

